//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rash_Airlines.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Flights_Schedule
    {
        [Display(Name = "Route ID")]
        public Nullable<int> route_id { get; set; }
        [Display(Name = "Departure Time")]
        public Nullable<System.TimeSpan> departure_time { get; set; }
        [Display(Name = "Arrival Time")]
        public Nullable<System.TimeSpan> arrival_time { get; set; }
        [Display(Name = "Duration")]
        public Nullable<System.TimeSpan> duration { get; set; }
        [Display(Name = "Flight ID")]
        public int flight_id { get; set; }
        [Display(Name = "Journey Date")]
        public System.DateTime journey_date { get; set; }
        [Display(Name = "Business Class")]
        public Nullable<int> bc_availability { get; set; }
        [Display(Name = "Economic Class")]
        public Nullable<int> ec_availability { get; set; }
    
        public virtual Flights_Master Flights_Master { get; set; }
        public virtual Routes_Master Routes_Master { get; set; }
    }
}
