//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectOnlineShopping.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class orderDetail
    {
        [Key]
        public int orderDetailsId { get; set; }
        [Required]
        public Nullable<int> orderId { get; set; }
        [Required]
        public Nullable<int> itemId { get; set; }
        [Required]
        public int quantity { get; set; }
        [Required]
        public int cost { get; set; }
    
        public virtual productDescription productDescription { get; set; }
        public virtual orderTable orderTable { get; set; }
    }
}
