//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectOnlineShopping.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class productDescription
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public productDescription()
        {
            this.carts = new HashSet<cart>();
            this.orderDetails = new HashSet<orderDetail>();
        }
        [Key]
        [Required]
        public int itemId { get; set; }
        [Required(ErrorMessage ="Category ID required")]
        [DisplayName("Select category Id")]
        public Nullable<int> categoryId { get; set; }

        [Required(ErrorMessage = "Product Name required")]
        [DisplayName("Enter the Name of the Product")]
        public string productName { get; set; }

        [Required(ErrorMessage = "Product Description required")]
        [DisplayName("Enter Description of the Product")]
        public string productDescription1 { get; set; }

        [Required(ErrorMessage = "Stock value required")]
        [DisplayName("Enter the stock value")]
        public int stock { get; set; }

       
        [DisplayName("Select the color")]
        public string color { get; set; }

        [Required(ErrorMessage = "Back Image required")]
        [DisplayName("upload Back Image")]
        public string backImage { get; set; }
    
        [Required(ErrorMessage = "Front Image required")]
        [DisplayName("upload Front Image")]
        public string frontImage { get; set; }
    
        [Required(ErrorMessage = "Side Image required")]
        [DisplayName("upload Side Image")]
        public string sideImage { get; set; }

        [Required(ErrorMessage = "Rating required")]
        [DisplayName("Enter the Ratings of the Product")]
        public Nullable<int> rating { get; set; }

        [Required(ErrorMessage = "Actual cost required")]
        [DisplayName("Enter the Actual cost")]
        public int actualCost { get; set; }
        [DisplayName("Enter the Discount")]
        public Nullable<int> discount { get; set; }

        [Required(ErrorMessage = "Current cost required")]
        [DisplayName("Enter the Current cost")]
        public int currentCost { get; set; }

        
        [DisplayName("Enter the Brand Name")]
        public string brand { get; set; }

        
        [DisplayName("Enter size")]
        public string size { get; set; }

        [Required(ErrorMessage = " Approval Status required")]
        [DisplayName("Enter the Approval Status")]
        public string approvalStatus { get; set; }

        [Required(ErrorMessage = "RetailerID required")]
        [DisplayName("Enter the RetailerID")]
        public Nullable<int> retailerId { get; set; }        

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cart> carts { get; set; }
        public virtual categoryDetail categoryDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orderDetail> orderDetails { get; set; }
        public virtual retailer retailer { get; set; }


        [NotMapped]
        [Required(ErrorMessage = "Quantity required")]
        [DisplayName("Enter Quantity")]
        public int quantity { get; set; }

    }
}
