//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectOnlineShopping.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class registrationTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public registrationTable()
        {
            this.carts = new HashSet<cart>();
            this.orderTables = new HashSet<orderTable>();
        }
        [Key]
        [Required (ErrorMessage ="Please enter your phone number")]
        [DisplayName("Phone Number")]
        public string phoneNo { get; set; }
        [Required(ErrorMessage = "Please enter Password")]
        [DisplayName("Password")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [NotMapped]
        [Required(ErrorMessage = "Please enter Password")]
        [Compare("Password",ErrorMessage ="Mismatch")]
        [DisplayName("Confirm Password")]
        [DataType(DataType.Password)]
        public string cnpass { get; set; }

        [Required(ErrorMessage = "Please enter Name")]
        [DisplayName("Name")]
        public string name { get; set; }
        [Required(ErrorMessage = "Please enter mail ID")]
        [DataType(DataType.EmailAddress)]
        [DisplayName("E-mail Id")]
        public string emailId { get; set; }
        [DisplayName("Address")]
        public string address { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cart> carts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orderTable> orderTables { get; set; }
    }
}
