//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectOnlineShopping.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class retailer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public retailer()
        {
            this.productDescriptions = new HashSet<productDescription>();
        }
        [Key]
       
        public int retailerId { get; set; }
        [Required(ErrorMessage = "Retailer phone number is required")]
        [DisplayName("Enter Retailer Phone NUmber")]
        public string phoneNo { get; set; }

        [Required(ErrorMessage = "Password is required")]
        [DisplayName("Enter Retailer Password")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [NotMapped]
        [Required(ErrorMessage = "Please enter Password")]
        [Compare("Password", ErrorMessage = "Mismatch")]
        [DisplayName("Confirm Password")]
        public string cnpass { get; set; }

        [Required(ErrorMessage = "Retailer Name is required")]
        [DisplayName("Enter Retailer Name")]
        public string name { get; set; }

        [Required(ErrorMessage = "Retailer's Email ID is required")]
        [DisplayName("Enter Email Id")]
        [DataType(DataType.EmailAddress)]
        public string emailId { get; set; }
        
        [DisplayName("Enter Address")]
        public string address { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<productDescription> productDescriptions { get; set; }
    }
}
