//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rash_Airlines.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int payment_id { get; set; }
        public string payment_status { get; set; }
        public Nullable<long> booking_id { get; set; }
        public Nullable<decimal> total_cost { get; set; }
    
        public virtual Passenger_booking_details Passenger_booking_details { get; set; }
    }
}
