//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmerApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SellRequest()
        {
            this.Adminapprovals = new HashSet<Adminapproval>();
            this.Biddings = new HashSet<Bidding>();
            this.Soldhistories = new HashSet<Soldhistory>();
        }
    
        public int Crop_ID { get; set; }
        public string Crop_type { get; set; }
        public string Crop_name { get; set; }
        public string Fertilizer { get; set; }
        public double Quantity { get; set; }
        public string Soil_PH { get; set; }
        public Nullable<double> Baseprice { get; set; }
        public Nullable<int> Farmer_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adminapproval> Adminapprovals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bidding> Biddings { get; set; }
        public virtual FarmerReg FarmerReg { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Soldhistory> Soldhistories { get; set; }
    }
}
