//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmerApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Soldhistory
    {
        public int Sold_ID { get; set; }
        public System.DateTime Date { get; set; }
        public int Crop_ID { get; set; }
        public string Crop_name { get; set; }
        public double Quantity { get; set; }
        public double Baseprice { get; set; }
        public double Soldprice { get; set; }
        public double Totalprice { get; set; }
    
        public virtual SellRequest SellRequest { get; set; }
    }
}
