CREATE TABLE TECHNOLOGY
(
TECHNOLOGY_ID INT PRIMARY KEY IDENTITY(1, 1),
TECHNOLOGY_NAME VARCHAR(10)
)

SELECT * FROM TECHNOLOGY

INSERT INTO TECHNOLOGY VALUES('JAVA')
INSERT INTO TECHNOLOGY VALUES('SQL')
INSERT INTO TECHNOLOGY VALUES('C#')
INSERT INTO TECHNOLOGY VALUES('PHP')
INSERT INTO TECHNOLOGY VALUES('PYTHON')
INSERT INTO TECHNOLOGY VALUES('C/C++')

DROP TABLE TECHNOLOGY