//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExamSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class USER_DETAIL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER_DETAIL()
        {
            this.REPORTs = new HashSet<REPORT>();
        }

        public int USERID { get; set; }
        [DisplayName("Full Name")]
        [Required(ErrorMessage = "Please enter your Name")]
        public string FULL_NAME { get; set; }
        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessage = "Please enter the EMAIL")]
        [DisplayName("Email")]
        public string EMAIL { get; set; }
        [DisplayName("Password")]
        [Required(ErrorMessage = "Please enter the Password")]
        [DataType(DataType.Password)]
        public string PASSWORD { get; set; }
        [DisplayName("Confirm Password")]
        [NotMapped]
        [DataType(DataType.Password)]
        [Compare("PASSWORD")]
        public string Confirm_Password { get; set; }
        [DisplayName("Mobile")]
        [Required(ErrorMessage = "Please enter your Mobile Number")]
        public string MOBILE { get; set; }
        [DisplayName("City")]
        [Required(ErrorMessage = "Please enter your City")]
        public string CITY { get; set; }
        [DisplayName("Date of Birth")]
        [Required(ErrorMessage = "Please enter your Date of Birth")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> DOB { get; set; }
        [DisplayName("State")]
        [Required(ErrorMessage = "Please enter your State")]
        public string STATE { get; set; }
        [DisplayName("Qualification")]
        [Required(ErrorMessage = "Please enter your Qualification")]
        public string QUALIFICATION { get; set; }
        [DisplayName("Year of Completion")]
        [Required(ErrorMessage = "Please enter the Year of Completion")]
        public Nullable<int> YEAR_OF_COMPLETION { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REPORT> REPORTs { get; set; }
    }
}
