//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBankingProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Beneficiary_Table
    {
        [DisplayName("Beneficiary Id")]
        public int Beneficiary_Id { get; set; }
        [DisplayName("Beneficiary Name")]
        public string Beneficiary_Name { get; set; }
        [DisplayName("Beneficiary Account Number")]
        public Nullable<long> Beneficiary_Account_Number { get; set; }
        [DisplayName("Nick Name")]
        public string Nick_Name { get; set; }

        [DisplayName("Account Number ")]
        public Nullable<long> Account_Number { get; set; }
    
        public virtual Open_Savings_Account Open_Savings_Account { get; set; }
    }
}
