//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBankingProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Open_Savings_Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Open_Savings_Account()
        {
            this.Beneficiary_Table = new HashSet<Beneficiary_Table>();
            this.Registration_table = new HashSet<Registration_table>();
            this.Transaction_Table = new HashSet<Transaction_Table>();
        }

        [DisplayName("Account Number")]

        public long Account_Number { get; set; }

        [DisplayName("First Name")]
       
        public string First_Name { get; set; }

        [DisplayName("Last Name")]
       
        public string Last_Name { get; set; }

        [DisplayName("Father Name")]
      
        public string Father_Name { get; set; }

        [DisplayName("Mobile Number")]
       
        public string Mobile_Number { get; set; }

        [DisplayName("Email Id")]
    
        public string Email_Id { get; set; }

        [DisplayName("AadharCard Number")]

        public string AadharCard_Number { get; set; }
        [DisplayName("Date Of Birth")]
        public Nullable<System.DateTime> Date_Of_Birth { get; set; }

        [DisplayName("Residential Address Line1")]
    
        public string Residential_Address_Line1 { get; set; }

        [DisplayName("Residential Address Line2")]
        
        public string Residential_Address_Line2 { get; set; }

        [DisplayName("LandMark")]
      
        public string Residential_Landmark { get; set; }

        [DisplayName("Residential State")]
       
        public string Residential_State { get; set; }

        [DisplayName("Residential City")]
       
        public string Residential_City { get; set; }

        [DisplayName(" Pincode")]
       
        public string Residential_Pincode { get; set; }

        [DisplayName("Permanent Address Line1")]
     
        public string Permanent_Address_Line1 { get; set; }
    
        [DisplayName("Permanent Address Line2")]
        public string Permanent_Address_Line2 { get; set; }

        [DisplayName(" Permanent Landmark ")]
    
        public string Permanent_Landmark { get; set; }

        [DisplayName("  Permanent State ")]
  
        public string Permanent_State { get; set; }

        [DisplayName("  Permanent City ")]
    
        public string Permanent_City { get; set; }

        [DisplayName("  Pincode")]
     
        public string Permanent_Pincode { get; set; }
   
        [DisplayName(" Occupational Type ")]
        public string Occupational_type { get; set; }

        [DisplayName(" Source Of Income ")]
  
        public string Source_Of_Income { get; set; }

        [DisplayName(" Gross Annual Income ")]
     
        public string Gross_Annual_income { get; set; }

        [DisplayName(" Balance ")]
        public Nullable<decimal> Balance { get; set; }

        [DisplayName(" Approve Status ")]
        
        public string Approve_Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Beneficiary_Table> Beneficiary_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Registration_table> Registration_table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction_Table> Transaction_Table { get; set; }
    }
}
