//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationQuestionnare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyActivity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DailyActivity()
        {
            this.DailyActivityTracks = new HashSet<DailyActivityTrack>();
            this.DailyEmployeeInterests = new HashSet<DailyEmployeeInterest>();
        }
    
        public int iDActivityID { get; set; }
        public string vDActivityName { get; set; }
        public Nullable<System.TimeSpan> tDDuration { get; set; }
        public Nullable<int> iStressMinLevel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyActivityTrack> DailyActivityTracks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyEmployeeInterest> DailyEmployeeInterests { get; set; }
    }
}
