//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationQuestionnare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyActivityTrack
    {
        public int DAT_number { get; set; }
        public string vEmpID { get; set; }
        public Nullable<int> iDActivityID { get; set; }
        public Nullable<System.DateTime> tDStartTime { get; set; }
        public Nullable<System.DateTime> tDStopTime { get; set; }
        public Nullable<bool> bDActivityStatus { get; set; }
        public Nullable<System.DateTime> dDActivityDate { get; set; }
    
        public virtual DailyActivity DailyActivity { get; set; }
        public virtual EmployeePersonalDetail EmployeePersonalDetail { get; set; }
    }
}
