//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationQuestionnare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Place
    {
        public int iPlaceID { get; set; }
        public Nullable<int> iWActivityID { get; set; }
        public string vPlaceName { get; set; }
        public string vDescription { get; set; }
        public string vLatitude { get; set; }
        public string vLongitude { get; set; }
        public string vCity { get; set; }
        public string vBestVisitingTime { get; set; }
        public string vImageLink { get; set; }
    
        public virtual WeekendActivity WeekendActivity { get; set; }
    }
}
