//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExamSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class QUESTION
    {
        public int QUESTION_ID { get; set; }
        [DisplayName("Technology")]
        public Nullable<int> TECHNOLOGY_ID { get; set; }
        [Required(ErrorMessage = "Question is Required")]
        [DisplayName("Question")]
        public string QUESTION1 { get; set; }
        [DisplayName("Option 1")]
        [Required(ErrorMessage = "Mention Option 1")]
        public string OPTION1 { get; set; }
        [DisplayName("Option 2")]
        [Required(ErrorMessage = "Mention Option 2")]
        public string OPTION2 { get; set; }
        [DisplayName("Option 3")]
        [Required(ErrorMessage = "Mention Option 3")]
        public string OPTION3 { get; set; }
        [DisplayName("Option 4")]
        [Required(ErrorMessage = "Mention Option 4")]
        public string OPTION4 { get; set; }
        [DisplayName("Right Answer")]
        [Required(ErrorMessage = "Give the right answer")]
        public Nullable<int> RIGHT_ANSWER { get; set; }
        [DisplayName("")]
        [NotMapped]
        public string Chosen_Answer { get; set; }
        [DisplayName("Test Level")]
        public Nullable<int> TEST_LEVEL { get; set; }

        public virtual TECHNOLOGY TECHNOLOGY { get; set; }
    }
}
