//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Lakshya
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_Lakshay_OnlinetestEntities : DbContext
    {
        public db_Lakshay_OnlinetestEntities()
            : base("name=db_Lakshay_OnlinetestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbl_FillBlank> tbl_FillBlank { get; set; }
        public virtual DbSet<tbl_MCQ> tbl_MCQ { get; set; }
        public virtual DbSet<tbl_Subjects> tbl_Subjects { get; set; }
        public virtual DbSet<tbl_Test> tbl_Test { get; set; }
        public virtual DbSet<tbl_TestReport> tbl_TestReport { get; set; }
        public virtual DbSet<tbl_Transaction> tbl_Transaction { get; set; }
        public virtual DbSet<tbl_TrueOrFalse> tbl_TrueOrFalse { get; set; }
        public virtual DbSet<tbl_User> tbl_User { get; set; }
    }
}
