//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Lakshya
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MCQ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_MCQ()
        {
            this.tbl_Transaction = new HashSet<tbl_Transaction>();
        }
    
        public string MCQ_Id { get; set; }
        public string MCQ_Ques { get; set; }
        public string Op_A { get; set; }
        public string Op_B { get; set; }
        public string Op_C { get; set; }
        public string Op_D { get; set; }
        public string Op_E { get; set; }
        public string MCQ_Ans_Key { get; set; }
        public string Sub_Id_MCQ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Transaction> tbl_Transaction { get; set; }
        public virtual tbl_Subjects tbl_Subjects { get; set; }
    }
}
