//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationQuestionnare
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageSet
    {
        public int ImageID { get; set; }
        public string ImagePath { get; set; }
        public string vOption1 { get; set; }
        public string vOption2 { get; set; }
        public string vOption3 { get; set; }
        public string vCorrectOption { get; set; }
    }
}
