//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rash_Airlines.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passenger_booking_details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Passenger_booking_details()
        {
            this.Payments = new HashSet<Payment>();
            this.Passengers_Details = new HashSet<Passengers_Details>();
            this.Passengers_Details_New = new HashSet<Passengers_Details_New>();
        }
    
        public long booking_id { get; set; }
        public int no_of_seats { get; set; }
        public string @class { get; set; }
        public Nullable<int> departure { get; set; }
        public Nullable<int> arrival { get; set; }
        public Nullable<int> flight_id { get; set; }
        public Nullable<int> passenger_id { get; set; }
        public Nullable<System.DateTime> booking_Date { get; set; }
        public Nullable<System.DateTime> journey_date { get; set; }
    
        public virtual Flights_Master Flights_Master { get; set; }
        public virtual Place Place { get; set; }
        public virtual Place Place1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Passengers_Details> Passengers_Details { get; set; }
        public virtual Passenger_Reg Passenger_Reg { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Passengers_Details_New> Passengers_Details_New { get; set; }
    }
}
