//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rash_Airlines.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Admin
    {
        public int admin_id { get; set; }
        [Display(Name = "Admin Username")]
        [Required(ErrorMessage = "Please fill this field")]
        public string admin_username { get; set; }
        [Display(Name = "Admin Password")]
        [Required(ErrorMessage = "Please fill this field")]
        [DataType(DataType.Password)]
        public string admin_password { get; set; }
    }
}
