//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rash_Airlines.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Passengers_Details
    {
        [Display(Name ="First Name")]
        [Required]
        public string first_name { get; set; }
        [Display(Name = "Last Name")]
       
        public string last_name { get; set; }
        [Display(Name = "Age")]
        [Required]
        public int age { get; set; }
        [Display(Name = "Seat No.")]
        public int seat_no { get; set; }
        public Nullable<int> passenger_id { get; set; }
        [Display(Name = "Booking ID ")]
        public Nullable<long> booking_id { get; set; }
        public Nullable<decimal> perhead_cost { get; set; }
        public byte[] status { get; set; }
    
        public virtual Passenger_booking_details Passenger_booking_details { get; set; }
        public virtual Passenger_Reg Passenger_Reg { get; set; }
    }
}
