//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rash_Airlines.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Passenger_Reg
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Passenger_Reg()
        {
            this.feedbacks = new HashSet<feedback>();
            this.Passenger_booking_details = new HashSet<Passenger_booking_details>();
            this.Passengers_Details = new HashSet<Passengers_Details>();
        }

        public int passenger_id { get; set; }
        [DisplayName("Title")]
        [Required(ErrorMessage ="Please fil this field")]
        public string title { get; set; }
        
        [DisplayName("First Name")]
        [Required(ErrorMessage = "Please fil this field")]
        public string first_name { get; set; }
        [DisplayName("Last Name")]
        [Required(ErrorMessage = "Please fil this field")]
        public string last_name { get; set; }
        
        [DisplayName("Email")]
        [Required(ErrorMessage = "Please fil this field")]
        public string email { get; set; }
       
        [DisplayName("Password")]
        [Required(ErrorMessage = "Please fil this field")]
        [DataType(DataType.Password)]        
        public string pwd { get; set; }
        //[DataType(DataType.Password)]
        [DisplayName("Confirm Password")]
        
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Please fil this field")]
        [Compare("pwd", ErrorMessage = "Password and Confirmation Password must match.")]
        public string confirm_pwd { get; set; }
        [DisplayName("Date Of Birth")]
        [Required(ErrorMessage = "Please fil this field")]
        public System.DateTime dob { get; set; }
        [DisplayName("Mobile")]
        [Required(ErrorMessage = "Please fil this field")]
        public string mobile { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<feedback> feedbacks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Passenger_booking_details> Passenger_booking_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Passengers_Details> Passengers_Details { get; set; }
    }
}
