//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rash_Airlines.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Passenger_booking_details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Passenger_booking_details()
        {
            this.Payments = new HashSet<Payment>();
            this.Passengers_Details = new HashSet<Passengers_Details>();
        }
        [Display(Name = "Booking ID")]
        public long booking_id { get; set; }
   
        [Display(Name = "Number Of Seats")]
        public int no_of_seats { get; set; }
      
        [Display(Name = "Class")]
        public string @class { get; set; }
        [Display(Name = "Departure")]
      
        public Nullable<int> departure { get; set; }
     
        [Display(Name = "Arrival")]
        public Nullable<int> arrival { get; set; }
        [Display(Name = "Flight ID")]
        public Nullable<int> flight_id { get; set; }
        [Display(Name = "Passenger ID")]
        public Nullable<int> passenger_id { get; set; }
        [Display(Name = "Booking Date")]
        
        public Nullable<System.DateTime> booking_Date { get; set; }
        [Display(Name = "Journey Date")]
   
        public Nullable<System.DateTime> journey_date { get; set; }
       
        public virtual Flights_Master Flights_Master { get; set; }
        public virtual Place Place { get; set; }
        public virtual Place Place1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Passengers_Details> Passengers_Details { get; set; }
        public virtual Passenger_Reg Passenger_Reg { get; set; }
    }
}
